server:
  port: 8071
spring:
  application:
    name: AppProductService
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: master
    password: hnytyhy682374
    url: jdbc:mysql://127.0.0.1:3306/product_service?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
env:
  dev
