server:
  port: 8072
spring:
  application:
    name: AppUserService
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: master
    password: hnytyhy682374
    url: jdbc:mysql://127.0.0.1:3306/user_service?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
  redis:
    host: localhost
    port: 6379
env:
  dev
